[package]
name = "mapstruct"
version = "0.3.0"
edition = "2021"
authors = ["Leon Camus"]
license = "MIT"
description = "Create refactor safe derivatives of Structs with proc-macros."

[dependencies]
mapstruct-derive = { path = "mapstruct-derive", version = "0.3.0" }
