[package]
name = "mapstruct-derive"
version = "0.2.0"
edition = "2021"
authors = ["Leon Camus"]
license = "MIT"
description = "A derive macro for the mapstruct crate"

[lib]
proc-macro = true

[dependencies]
mapstruct-derive-lib = { path = "../mapstruct-derive-lib", version = "0.2.0" }
