[package]
name = "mapstruct-derive-lib"
version = "0.4.0"
edition = "2021"
authors = ["Leon Camus"]
license = "MIT"
description = "A derive macro for mapstruct"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
